# --------------------------- #
# SETTINGS SECTION
# --------------------------- #
SETTINGS:
    # number of concurrent threads
    THREADS: 1
    # number of retries for ANY action
    ATTEMPTS: 5
    # account range.
    # BY DEFAULT: [0, 0] - all accounts
    # [3, 5] - only 3 4 5 accounts
    # [7, 7] - only 7 account
    ACCOUNTS_RANGE: [0, 0]
    # WORKS ONLY IF ACCOUNTS_RANGE IS [0, 0]
    # exact accounts to use. 
    # BY DEFAULT: [] - all accounts
    # Example: [1, 4, 6] - bot will use only 1, 4 and 6 accounts
    EXACT_ACCOUNTS_TO_USE: []
    # pause between attempts
    PAUSE_BETWEEN_ATTEMPTS: [5, 15]
    # pause between swaps
    PAUSE_BETWEEN_SWAPS: [10, 40]
    # pause in seconds between accounts
    RANDOM_PAUSE_BETWEEN_ACCOUNTS: [3, 15]
    # pause in seconds between actions
    RANDOM_PAUSE_BETWEEN_ACTIONS: [3, 10]
    # random pause before start of every account
    # to make sure that all accounts will be started at different times
    RANDOM_INITIALIZATION_PAUSE: [1, 2]
    # pause multiplier for browser actions
    BROWSER_PAUSE_MULTIPLIER: 1.5
    # telegram settings
    TELEGRAM_BOT_TOKEN: ''
    TELEGRAM_USERS_IDS: []

# --------------------------- #
# FLOW SECTION
# --------------------------- #
FLOW:
    # number of swaps. bean ambient monad etc
    NUMBER_OF_SWAPS: [1, 3]
    # percent of balance to swap
    PERCENT_OF_BALANCE_TO_SWAP: [10, 15]

# --------------------------- #
# OTHER SECTIONS
# --------------------------- #
DISPERSE:
    # if balance of main account is LESS than this value
    # bot will disperse tokens from farm accounts to main account
    MIN_BALANCE_FOR_DISPERSE: [0.2, 0.5]

APRIORI:
    AMOUNT_TO_STAKE: [0.0001, 0.0003]

MAGMA:
    AMOUNT_TO_STAKE: [0.0001, 0.0003]

KINTSU:
    # MINIMUM IS 0.01 $MON
    AMOUNT_TO_STAKE: [0.01, 0.02]

BIMA:
    LEND: true
    PERCENT_OF_BALANCE_TO_LEND: [20.0, 30.0]

GASZIP:
    NETWORKS_TO_REFUEL_FROM: ["Arbitrum", "Base", "Optimism"]
    AMOUNT_TO_REFUEL: [0.0001, 0.00015]
    MINIMUM_BALANCE_TO_REFUEL: 0.5
    WAIT_FOR_FUNDS_TO_ARRIVE: true
    MAX_WAIT_TIME: 999999

MEMEBRIDGE:
    NETWORKS_TO_REFUEL_FROM: ["Arbitrum", "Base", "Optimism"]
    AMOUNT_TO_REFUEL: [0.0001, 0.00015]
    MINIMUM_BALANCE_TO_REFUEL: 0.5
    WAIT_FOR_FUNDS_TO_ARRIVE: true
    MAX_WAIT_TIME: 999999

TESTNET_BRIDGE:
    NETWORKS_TO_REFUEL_FROM: ["Arbitrum", "Optimism"]
    AMOUNT_TO_REFUEL: [0.0002, 0.0003]
    MINIMUM_BALANCE_TO_REFUEL: 5.0
    WAIT_FOR_FUNDS_TO_ARRIVE: true
    MAX_WAIT_TIME: 999999

SHMONAD:
    BUY_AND_STAKE_SHMON: true
    UNSTAKE_AND_SELL_SHMON: true
    # percent of balance to swap on shmonad.xyz
    PERCENT_OF_BALANCE_TO_SWAP: [2, 3]

ACCOUNTABLE:
    NFT_PER_ACCOUNT_LIMIT: 3

ORBITER:
    AMOUNT_TO_BRIDGE: [0.1, 0.2]
    BRIDGE_ALL: true
    WAIT_FOR_FUNDS_TO_ARRIVE: true
    MAX_WAIT_TIME: 999999999

LILCHOGSTARS:
    MAX_AMOUNT_FOR_EACH_ACCOUNT: [1, 3]

DEMASK:
    MAX_AMOUNT_FOR_EACH_ACCOUNT: [1, 3]

# monadking or monadking_unlocked
MONADKING:
    MAX_AMOUNT_FOR_EACH_ACCOUNT: [1, 3]

MAGICEDEN:
    NFT_CONTRACTS: [
        "0xb81fbb4362a586fdb3edfe261b2e1bbe73e6cd67",  # 0.01 $MON
        "0x281df2c9178aa2dfd229771ef8f03cce90e60373",  # 0.01 $MON
        "0x002c8fd766605b609d31cc9764e27289daf033e9",  # 0.001 $MON
        "0x471af5eb201adc7851f4abec99ba1c78e51de0ce",  # 0.01 $MON
        "0x63300257926af6f2a1bf2d4efb4240d8d8f250d6",  # free
        "0xfd3b54bd826cea09d15e87f95a869ecf3e462f92",  # free
        "0xb2ea0ff3ad4134367fb7dc75d48b3493e5a09c81",
        "0x74e9115cfcaa5edbfc6670139c0b2a2833fc64ed",
        "0xdecbb47872961d27275d68ae651e1956ef609f42"
    ]

FAUCET:
    CAPSOLVER_API_KEY: CAP-
